user_project/user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path('registration/', views.RegistrationView, name='registration'),
    path('home/', views.home, name='home'),
    path('login/', views.user_login, name='user_login'),
    path('logout', views.user_logout, name='user_logout'),



]

user_project/user_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_app/', include('user_app.urls'))
]

user_project/user_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

user_project/user_app/forms.py
from django.contrib.auth.models import User
from .models import UserProfileInfo
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

user_project/user_app/views.py
from django.shortcuts import render
from .forms import UserProfileInfoForm, UserForm
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.




def home(request):
    return render(request, 'user_app/home.html')

def RegistrationView(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()


            try:
                validate_password(user.password, user)
            except ValidationError as e:
                user_form.add_error('password', e)
                return render(request, 'user_app/registration.html', {'user_form': user_form,
                                                                      'profile_form': profile_form,
                                                                      'registered': registered})

            user.set_password(user.password)

            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)


    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'user_app/registration.html', {'user_form':user_form,
                                                          'profile_form' : profile_form,
                                                          'registered':registered})



def user_login(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('user_app:home'))

            else:
                    return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print("Someone tried to login")
            return HttpResponse("INVALID LOGIN DETAILS")
    else:
        return render(request, 'user_app/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_app:home'))

user_project/user_app/templates/user_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


  </head>

  <body>


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">USER_PROJECT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'user_app:user_logout' %}">Logout <span class="sr-only">(current)</span></a>
        {% else %}
          <a class="nav-link" href="{% url 'user_app:user_login' %}">Login <span class="sr-only">(current)</span></a>
        {% endif %}
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>



  </body>
</html>

user_project/user_app/templates/user_app/home.html
<!DOCTYPE html>
{% extends "user_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>HOME PAGE</h1>
</div>

{% endblock %}

user_project/user_app/templates/user_app/login.html
<!DOCTYPE html>
{% extends "user_app/base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'user_app:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" placeholder="Enter Username">

    <label for="password">Password::</label>
    <input type="text" id="password" name="password">

    <input type="submit" name="" value="login">

  </form>


</div>




{% endblock %}

user_project/user_app/templates/user_app/registration.html
<!DOCTYPE html>
{% extends "user_app/base.html" %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
      <h1>Register here:</h1>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name ="" value="Register">


      </form>
      {% endif %}


  </div>
{% endblock %}